[package]
name = "simplex-23d-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "simplex_23d"
path = "src/lib.rs"

[dependencies]
rand = "0.8"

[dev-dependencies]
image = "0.24"
plotters = "0.3"
criterion = { version = "0.4" }

[[bench]]
name = "simplex_benchmark"
harness = false